# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c5167310f9f3736e5ffdec67ba886a9d746b1bb6ac6248ba2338ad80174e61f25f22b9d09531f2e1f56007da7cbf317958b0f0bf92f098abe8bbd3123b72152

test:
  secret_key_base: 5c96242d332286fbfac679c1137d627929dd1fef0d11c317e8c4b38a0cd1237f6ec803cb90f45c19e5a3448d4fafa0cdccf15b1b7979f9492635acf47d2b54d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
